apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas-gateway-service
  namespace: cas
  labels:
    app.kubernetes.io/name: cas-gateway-service
    app.kubernetes.io/instance: cas-gateway-service
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: tanzu-base-projects
  annotations:
    argocd.argoproj.io/sync-options: Replace=true

spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: cas-gateway-service
      app.kubernetes.io/instance: cas-gateway-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cas-gateway-service
        app.kubernetes.io/instance: cas-gateway-service
        app.kubernetes.io/component: backend
    spec:
      imagePullSecrets:
        - name: ghcr-regcred
      securityContext:
        runAsNonRoot: true
        runAsUser: 1003
        runAsGroup: 1003
        fsGroup: 1003
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: cas-gateway-service
                    app.kubernetes.io/instance: cas-gateway-service
                topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: cas-gateway-service
              app.kubernetes.io/instance: cas-gateway-service
      containers:
        - name: cas-gateway-service
          image: ghcr.io/sampathbankplc/cas-gateway-service:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
#          readinessProbe:
#            httpGet:
#              path: /cas-lead/actuator/health
#              port: http
#            initialDelaySeconds: 15
#            periodSeconds: 10
#            timeoutSeconds: 2
#            failureThreshold: 3
#          livenessProbe:
#            httpGet:
#              path: /cas-lead/actuator/health
#              port: http
#            initialDelaySeconds: 15
#            periodSeconds: 20
#            timeoutSeconds: 2
#            failureThreshold: 3
          volumeMounts:
            - name: logs
              mountPath: /app/logs
              readOnly: false
            - name: cert-volume
              mountPath: /app/certs
              readOnly: true
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: secrets
              mountPath: /app/secrets
              readOnly: true
          env:
            - name: TZ
              value: Asia/Colombo
#            - name: SPRING_DATASOURCE_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: cas-lead-secrets
#                  key: username
#            - name: SPRING_DATASOURCE_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: cas-lead-secrets
#                  key: password
#            - name: SPRING_DATASOURCE_URL
#              valueFrom:
#                secretKeyRef:
#                  name: cas-lead-secrets
#                  key: jdbc-url
#            - name: CERT_PATH
#              valueFrom:
#                secretKeyRef:
#                  name: cas-lead-secrets
#                  key: cert-path
#            - name: CERT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: cas-lead-secrets
#                  key: cert-password
#            - name: ENC_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: cas-lead-secrets
#                  key: enc-key
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: nfs-pvc-cas-gateway-service
        - name: cert-volume
          persistentVolumeClaim:
            claimName: shared-cert-pvc-cas-gateway-service
        - name: config
          configMap:
            name: cas-gateway-service-env-config
        - name: secrets
          secret:
            secretName: cas-gateway-service-secrets