apiVersion: v1
kind: Service
metadata:
  name: cas-gateway-service
  namespace: cas
  labels:
    app.kubernetes.io/name: cas-gateway-service
    app.kubernetes.io/instance: cas-gateway-service
    app.kubernetes.io/component: backend
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.241.89
  selector:
    app.kubernetes.io/name: cas-gateway-service
    app.kubernetes.io/instance: cas-gateway-service
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP