apiVersion: v1
kind: Secret
metadata:
  name: cas-gateway-service-secrets
  namespace: cas
type: Opaque
#data:
#  jdbc-url: ZGJjOm9yYWNsZTp0aGluOkBkYzJ0c3Qtc2Nhbi5zYW1wYXRoLmxrOjE1MjMvdGNtbmRi
#  username: Y2FzdjJhcG4=
#  password: RU5DKGVnbmF6YjhoOUxvbGhtNjd6b0tKZTBqd25RbW9sYzZVKQ==
#  enc-key: a0ZPZUh2cG5pNVhtTDJTTzVxSGwrU245dHZLUGRGb1RyZXgwZTA2cUN3dk1YQm1laGJSYkl3NHA4ZlhVMENsQmtuc0ovV0JhV25GNjZuSE1zRW84SS85RVVUb24vTHdwVTM0ZUF6NElIL3JzMS9NWTZMNEJ2bzUwYlZ4MkhJSXplamx4dWk3cnc4dC9jcTJCYjNxR084M201dXBjYnp5Umx3TWhURnhoTmtKMzVTenpwWjQvY2FlZ0xUZlZKYnpPNXhZak4wN0NoSWZrQUtIUjJZUVdtRHdvc1hWajRoQWpkcFZZS3JPRzBkNENFbEpMb0tUUmlCdHRNQmd0N1Bwa08yaDlIK1FLUkpBaGtsR0VsdE9kV08xNzZzWS9xL2cyN0EzbzhyMitZVHVJR3hIUTA2dkh0N2tZNm0zVVFjNitHaGRsNWphM3NZSFVMZXo3bnEzTS93PT0=
#  cert-path: L2FwcC9jZXJ0cy9TYW1wYXRoQmFuay5wMTI=
#  cert-password: cGFzc3dvcmQ=